### ISSUE TITLE
issue during docker build

### ISSUE THREAD

**Issue by JonanekDev** [NexvisionLab/Darkweb-search-engine#15]
Hi, tried to build your intresting app for docker, but the docker build failed, i dnd't touch any of the dockerfiles of the project, just run the build and, got erros. OS: Debian 12, newest Docker 
```
46.82   Downloading Twisted-20.3.0.tar.bz2 (3.1 MB)
47.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 3.1 MB/s eta 0:00:00
49.75   Preparing metadata (setup.py): started
82.32   Preparing metadata (setup.py): finished with status 'error'
82.33   error: subprocess-exited-with-error
82.33   
82.33   × python setup.py egg_info did not run successfully.
82.33   │ exit code: 1
82.33   ╰─> [34 lines of output]
82.33       Traceback (most recent call last):
82.33         File "<string>", line 2, in <module>
82.33         File "<pip-setuptools-caller>", line 34, in <module>
82.33         File "/tmp/pip-install-ahbvlhey/twisted_032a14b845ac45f8a4d14cff892f8761/setup.py", line 20, in <module>
82.33           setuptools.setup(**_setup["getSetupArgs"]())
82.33         File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
82.33           return distutils.core.setup(**attrs)
82.33         File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
82.33           _setup_distribution = dist = klass(attrs)
82.33         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
82.33           _Distribution.__init__(self, {
82.33         File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
82.33           self.finalize_options()
82.33         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
82.33           ep.load()(self)
82.33         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
82.33           ep.load()(self, ep.name, value)
82.33         File "/tmp/pip-install-ahbvlhey/twisted_032a14b845ac45f8a4d14cff892f8761/.eggs/incremental-24.7.1-py3.8.egg/incremental/__init__.py", line 423, in _get_distutils_version
82.33           sp_command.finalize_options()
82.33         File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 34, in finalize_options
82.33           orig.build_py.finalize_options(self)
82.33         File "/usr/lib/python3.8/distutils/command/build_py.py", line 43, in finalize_options
82.33           self.set_undefined_options('build',
82.33         File "/usr/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
82.33           src_cmd_obj = self.distribution.get_command_obj(src_cmd)
82.33         File "/usr/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
82.33           klass = self.get_command_class(command)
82.33         File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 834, in get_command_class
82.33           self.cmdclass[command] = cmdclass = ep.load()
82.33         File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
82.33           return self.resolve()
82.33         File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
82.33           module = __import__(self.module_name, fromlist=['__name__'], level=0)
82.33       ModuleNotFoundError: No module named 'setuptools.command.build'
82.33       [end of output]
82.33   
82.33   note: This error originates from a subprocess, and is likely not a problem with pip.
82.33 error: metadata-generation-failed
82.33 
82.33 × Encountered error while generating package metadata.
82.33 ╰─> See above for output.
82.33 
82.33 note: This is an issue with the package mentioned above, not pip.
82.33 hint: See above for details.
------
Dockerfile:40
--------------------
  38 |     COPY requirements.txt /opt/torscraper
  39 |     RUN python -m pip install --upgrade pip
  40 | >>> RUN pip install --no-cache-dir -r requirements.txt
  41 |     RUN pip install --upgrade requests
  42 |     
--------------------
```

**Comment by DRIgnazGortngschirl** [comment]
Hi @JonanekDev 

Give this forked repo https://github.com/Gharib110/Darkweb-search-engine a shot. For me, it builds but still facing some issues described in https://github.com/NexvisionLab/Darkweb-search-engine/issues/16
