### ISSUE TITLE
The web-general docker image in crashloop

### ISSUE THREAD

**Issue by ak2766** [NexvisionLab/Darkweb-search-engine#16]
To get the `docker compose build` to complete successfully, I had to remove version numbers for the following packages:

```
attrs
pydantic
Twisted
zope.interface
```

Additionally, after running `docker compose up`, the `darkweb-search-engine-web-general` container enters a crash loop.

<details>
<summary>Web General Container Crash Log</summary>

```
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
Cannot import language library.
Traceback (most recent call last):
  File "/opt/torscraper/web/app.py", line 13, in <module>
    from tor_db import *
  File "/opt/torscraper/lib/tor_db/__init__.py", line 15, in <module>
    from tor_db.models import *
  File "/opt/torscraper/lib/tor_db/models/__init__.py", line 1, in <module>
    from tor_db.models.domain import *
  File "/opt/torscraper/lib/tor_db/models/domain.py", line 10, in <module>
    import bitcoin
  File "/opt/torscraper/lib/bitcoin.py", line 9, in <module>
    import coinaddr
  File "/usr/local/lib/python3.8/site-packages/coinaddr/__init__.py", line 21, in <module>
    from . import interfaces, currency, validation
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 44, in <module>
    class ValidatorBase(metaclass=ValidatorMeta):
  File "/usr/local/lib/python3.8/site-packages/coinaddr/validation.py", line 53, in ValidatorBase
    attr.validators.provides(IValidationRequest)
AttributeError: module 'attr.validators' has no attribute 'provides'
```
</details>

**Comment by ak2766** [comment]
FYI: This is on Ubuntu 24.04 host.  I'll try again on Ubuntu 20.04 to see if I can get a different outcome.

**Comment by Gharib110** [comment]
yes I have forked it and made some changes, even I built some of its docker images but I still have problem with web general.
https://github.com/Gharib110/Darkweb-search-engine

**Comment by ak2766** [comment]
Same outcome on Ubuntu 20.04.  Hopefully there's help around the corner...

**Comment by DRIgnazGortngschirl** [comment]
@Gharib110 Thanks for your forked repo! Helped me build the images successfully. 

I am also hitting the same error as well as db connection timeouts, do you as well ? 


```
darkweb-search-engine-db               | 2024-11-02  0:07:59 136347027695360 [Warning] Aborted connection 186 to db: 'tor' user: 'toruser' host: '172.16.57.18' (Got an error reading communication packets)
darkweb-search-engine-db               | 2024-11-02  0:08:09 136347027695360 [Warning] Aborted connection 188 to db: 'tor' user: 'toruser' host: '172.16.57.6' (Got an error reading communication packets)
darkweb-search-engine-db               | 2024-11-02  0:08:22 136347027695360 [Warning] Aborted connection 190 to db: 'tor' user: 'toruser' host: '172.16.57.6' (Got an error reading communication packets)
darkweb-search-engine-db               | 2024-11-02  0:08:35 136347027695360 [Warning] Aborted connection 192 to db: 'tor' user: 'toruser' host: '172.16.57.6' (Got an error reading communication packets)
darkweb-search-engine-db               | 2024-11-02  0:08:48 136347027695360 [Warning] Aborted connection 194 to db: 'tor' user: 'toruser' host: '172.16.57.6' (Got an error reading communication packets)
darkweb-search-engine-db               | 2024-11-02  0:09:01 136347027695360 [Warning] Aborted connection 196 to db: 'tor' user: 'toruser' host: '172.16.57.6' (Got an error reading communication packets)
```

**Comment by DRIgnazGortngschirl** [comment]
Seems that I fixed the web-general container crash loop by modifying the requirements.txt in web-general and setting a specific version. I just tried 21.4.0 with wich I did not encounter any crash since. 

```diff
-attrs
+attrs==21.4.0
```

Just still having issues with the db connect, trying from inside a container to db works just fine.

**Comment by Gharib110** [comment]
Thanks for your fixing that. Yes I could not connect to the database too. I will try to fix it.

**Comment by DRIgnazGortngschirl** [comment]
HI ! @Gharib110 Have you looked into it yet ?
