### ISSUE TITLE
build and running docker failed on a kali and on MAC

### ISSUE THREAD

**Issue by littlAcen** [NexvisionLab/Darkweb-search-engine#17]
Collecting Twisted==20.3.0 (from -r requirements.txt (line 100))
  Downloading Twisted-20.3.0.tar.bz2 (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gsymogct/twisted_6814468196f742938763d915ce433ea0/setup.py", line 20, in <module>
          setuptools.setup(**_setup["getSetupArgs"]())
        File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
          _Distribution.__init__(self, {
        File "/usr/local/lib/python3.8/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 807, in finalize_options
          ep(self)
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-install-gsymogct/twisted_6814468196f742938763d915ce433ea0/.eggs/incremental-24.7.2-py3.8.egg/incremental/__init__.py", line 438, in _get_distutils_version
          sp_command.finalize_options()
        File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_py.py", line 37, in finalize_options
          orig.build_py.finalize_options(self)
        File "/usr/local/lib/python3.8/distutils/command/build_py.py", line 43, in finalize_options
          self.set_undefined_options('build',
        File "/usr/local/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
          src_cmd_obj = self.distribution.get_command_obj(src_cmd)
        File "/usr/local/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
          klass = self.get_command_class(command)
        File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 854, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
          return self.resolve()
        File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'web-general' failed to build : Build failed
                                                                                                                                                                         
┌──(root㉿kali-data)-[/home/jamy/Downloads/Darkweb-search-engine]
└─#

**Comment by DRIgnazGortngschirl** [comment]
Hey @littlAcen 

Give this forked repo https://github.com/Gharib110/Darkweb-search-engine  a shot. For me it build but still faceing some issues described in https://github.com/NexvisionLab/Darkweb-search-engine/issues/16
